sudo: false
language: node_js
node_js:
  - 0.12
  - 4
  - node
env:
  - ARANGODB_VERSION=2.8 ARANGO_VERSION=20800
  - ARANGODB_VERSION=3.0 ARANGO_VERSION=30000
  - ARANGODB_VERSION=devel ARANGO_VERSION=30100
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash
script:
  - npm run lint && npm run dist && npm run coveralls
