name: Resilience & Failover CI

on:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  resilience-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install ArangoDB
        run: |
          curl -OL https://download.arangodb.com/arangodb36/DEBIAN/Release.key
          sudo apt-key add - < Release.key
          echo 'deb https://download.arangodb.com/arangodb36/DEBIAN/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
          sudo apt-get install apt-transport-https
          sudo apt-get update
          sudo apt-get install arangodb3
          sudo service arangodb3 stop
      - run: yarn
      - run: yarn test
        env:
          RESILIENCE_ARANGO_BASEPATH: 1
          CI: true
