name: Continuous Integration

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]
        arangodb-version: [3.5, 3.6, 3.7]

    container:
      image: node:${{ matrix.node-version }}

    services:
      arangodb:
        image: arangodb:${{ matrix.arangodb-version }}
        env:
          ARANGO_NO_AUTH: 1

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
        env:
          TEST_ARANGODB_URL: http://arangodb:8529
          CI: true
