name: Continuous Integration

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        arangodb-version: [3.5, 3.6]
        
    services:
      arangodb:
        image: arangodb:${{ matrix.arangodb-version }}
        env:
          ARANGO_NO_AUTH: 1

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn && yarn build
    - run: yarn test
      env:
        TEST_ARANGODB_URL: http://arangodb:8529
        CI: true
