name: Browser Smoke Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arangodb-version: [3.5, 3.6, 3.7]

    container:
      image: buildkite/puppeteer:latest

    services:
      arangodb:
        image: arangodb:${{ matrix.arangodb-version }}
        env:
          ARANGO_NO_AUTH: 1

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: node smoke-test.js
